// <auto-generated />
using System;
using HowToSoftware.Hosting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HowToSoftware.Hosting.Data.CommerceMigrations
{
    [DbContext(typeof(CommerceDbContext))]
    partial class CommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.BillingInvoiceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountDueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_due_cents");

                    b.Property<long>("AmountPaidCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid_cents");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_profile_id");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("hosted_invoice_url");

                    b.Property<Guid?>("HostingServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hosting_service_id");

                    b.Property<DateTimeOffset?>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoicePdfUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("invoice_pdf_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_invoice_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("HostingServiceId");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("CustomerProfileId", "InvoiceDate");

                    b.ToTable("billing_invoice_refs", t =>
                        {
                            t.HasCheckConstraint("ck_billing_invoice_refs_amounts", "amount_due_cents >= 0 AND amount_paid_cents >= 0");
                        });
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CommerceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ArtworkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("artwork_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<bool>("PrimaryGame")
                        .HasColumnType("boolean")
                        .HasColumnName("primary_game");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Active", "PrimaryGame");

                    b.ToTable("games");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CommerceHostingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("AllocationLimit")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_limit");

                    b.Property<int>("BackupLimit")
                        .HasColumnType("integer")
                        .HasColumnName("backup_limit");

                    b.Property<int>("CpuPercent")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DatabaseLimit")
                        .HasColumnType("integer")
                        .HasColumnName("database_limit");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DiskMb")
                        .HasColumnType("integer")
                        .HasColumnName("disk_mb");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("MonthlyPriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("monthly_price_cents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("RamMb")
                        .HasColumnType("integer")
                        .HasColumnName("ram_mb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("GameId", "Active", "SortOrder");

                    b.ToTable("hosting_plans", t =>
                        {
                            t.HasCheckConstraint("ck_hosting_plans_limits", "allocation_limit >= 0 AND database_limit >= 0 AND backup_limit >= 0");

                            t.HasCheckConstraint("ck_hosting_plans_price", "monthly_price_cents >= 0");

                            t.HasCheckConstraint("ck_hosting_plans_resources", "ram_mb > 0 AND cpu_percent > 0 AND disk_mb > 0");
                        });
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CommerceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BaseAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("base_amount_cents");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<Guid?>("CustomerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_profile_id");

                    b.Property<long>("DiscountAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount_cents");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<long>("FinalAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("final_amount_cents");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("GameSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_slug");

                    b.Property<string>("HtsUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hts_user_id");

                    b.Property<long>("MonthlyPriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("monthly_price_cents");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("plan_name");

                    b.Property<string>("PlanSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_slug");

                    b.Property<string>("ProvisioningStage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provisioning_stage");

                    b.Property<string>("ServerIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("server_identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_checkout_session_id");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_invoice_id");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("SubscriptionStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("StripeCheckoutSessionId")
                        .IsUnique();

                    b.HasIndex("StripeSubscriptionId");

                    b.ToTable("orders", t =>
                        {
                            t.HasCheckConstraint("ck_orders_amounts", "monthly_price_cents >= 0 AND base_amount_cents >= 0 AND discount_amount_cents >= 0 AND final_amount_cents >= 0");

                            t.HasCheckConstraint("ck_orders_discount", "discount_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("HtsUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hts_user_id");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HtsUserId")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId")
                        .IsUnique();

                    b.ToTable("customer_profiles");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.DeploymentEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("HostingServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hosting_service_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("ProvisioningJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioning_job_id");

                    b.HasKey("Id");

                    b.HasIndex("HostingServiceId");

                    b.HasIndex("ProvisioningJobId", "CreatedAt");

                    b.ToTable("deployment_events");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.GameDeploymentProfileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultStartup")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("default_startup");

                    b.Property<string>("DeploymentConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deployment_config_json");

                    b.Property<string>("DockerImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("docker_image");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("PterodactylEggId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_egg_id");

                    b.Property<int>("PterodactylNestId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_nest_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasFilter("active");

                    b.ToTable("game_deployment_profiles");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.HostingNodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location");

                    b.Property<bool>("Maintenance")
                        .HasColumnType("boolean")
                        .HasColumnName("maintenance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("PterodactylNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_node_id");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region");

                    b.PrimitiveCollection<string[]>("SupportedGames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("supported_games");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PterodactylNodeId")
                        .IsUnique();

                    b.HasIndex("Enabled", "Maintenance", "Priority");

                    b.ToTable("hosting_nodes");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.HostingServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_profile_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int?>("PterodactylNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_node_id");

                    b.Property<int?>("PterodactylServerId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_server_id");

                    b.Property<string>("PterodactylServerUuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pterodactyl_server_uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("PterodactylServerId")
                        .IsUnique();

                    b.HasIndex("PterodactylServerUuid")
                        .IsUnique();

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.HasIndex("CustomerProfileId", "Status");

                    b.ToTable("hosting_services");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.PlanBillingPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("StripeProductId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_product_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StripePriceId")
                        .IsUnique();

                    b.HasIndex("PlanId", "BillingPeriod")
                        .IsUnique();

                    b.ToTable("plan_billing_prices", t =>
                        {
                            t.HasCheckConstraint("ck_plan_billing_prices_amount", "amount_cents >= 0");

                            t.HasCheckConstraint("ck_plan_billing_prices_discount", "discount_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_plan_billing_prices_period", "billing_period IN ('monthly', 'quarterly', 'annual')");
                        });
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.ProvisioningJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostingServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hosting_service_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int?>("PterodactylServerId")
                        .HasColumnType("integer")
                        .HasColumnName("pterodactyl_server_id");

                    b.Property<string>("PterodactylServerUuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pterodactyl_server_uuid");

                    b.Property<int?>("SelectedNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("selected_node_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HostingServiceId")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("provisioning_jobs", t =>
                        {
                            t.HasCheckConstraint("ck_provisioning_jobs_attempts", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.StripeEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("processing_error");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_event_id");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.HasIndex("Processed", "ReceivedAt");

                    b.ToTable("stripe_events");
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.BillingInvoiceReference", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.HostingServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("HostingServiceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CommerceHostingPlan", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.CommerceOrder", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceHostingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.DeploymentEventRecord", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.HostingServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("HostingServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.ProvisioningJobRecord", null)
                        .WithMany()
                        .HasForeignKey("ProvisioningJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.GameDeploymentProfileRecord", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.HostingServiceRecord", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceHostingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.PlanBillingPrice", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceHostingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Commerce.ProvisioningJobRecord", b =>
                {
                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.HostingServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("HostingServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowToSoftware.Hosting.Models.Commerce.CommerceOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
