// <auto-generated />
using System;
using HowToSoftware.Hosting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HowToSoftware.Hosting.Data.Migrations
{
    [DbContext(typeof(HostingDbContext))]
    [Migration("20260907203618_InitialOrders")]
    partial class InitialOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProvisioningStage")
                        .HasColumnType("int");

                    b.Property<string>("ServerIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SubscriptionStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StripeCheckoutSessionId")
                        .IsUnique()
                        .HasFilter("[StripeCheckoutSessionId] IS NOT NULL");

                    b.HasIndex("StripeSubscriptionId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("HowToSoftware.Hosting.Models.Orders.ProcessedStripeEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.ToTable("ProcessedStripeEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
